[project]
name = "grasp-agents-example-demo-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.4,<3.12"
dependencies = ["grasp-agents>=0.1.9"]

[dependency-groups]
dev = ["ruff>=0.11.8"]
