[project]
name = "grasp_agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.4,<3.12"
dependencies = [
    "httpx>=0.28.1",
    "openai>=1.77.0",
    "pre-commit-uv>=4.1.4",
    "pydantic>=2.11.4",
    "ruff>=0.11.8",
    "tenacity>=9.1.2",
    "termcolor>=3.1.0",
]
