[project]
name = "grasp_agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.4,<3.12"
dependencies = [
    "httpx>=0.28.1",
    "ipykernel>=6.29.5",
    "openai>=1.77.0",
    "pre-commit-uv>=4.1.4",
    "pydantic>=2.11.4",
    "ruff>=0.11.8",
    "tenacity>=9.1.2",
    "termcolor>=2.4.0,<3",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["src/grasp_agents"]
exclude = ["src/grasp_agents/examples", "*.ipynb"]

[tool.hatch.build.targets.wheel]
packages = ["src/grasp_agents"]
exclude = ["src/grasp_agents/examples", "*.ipynb"]
