services:
  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"  # UI and OTLP HTTP collector
      - "4317:4317"  # OTLP gRPC collector
    environment:
      - PHOENIX_WORKING_DIR=/phoenix_data
    volumes:
      - type: bind
        source: /Users/john_doe/phoenix_data # Change this to your desired local path
        target: /phoenix_data # Ensure this matches PHOENIX_WORKING_DIR
